use my_db;

## IST SHEET :

SELECT AVG(SAL) AS Avg_Sal_of_Clerk FROM emp WHERE JOB = "CLERK";
SELECT MGR,SUM(SAL) AS Total_Sal FROM emp WHERE MGR IS NOT NULL GROUP BY MGR;
SELECT MAX(SAL) FROM emp;
SELECT COUNT(*) FROM emp WHERE JOB = "CLERK" AND DEPTNO = 20;
SELECT COUNT(*) FROM emp WHERE JOB = "MANAGER";
SELECT EMPNO,ENAME FROM emp WHERE JOB = "CLERK" ORDER BY SAL LIMIT 1;
SELECT EMPNO,ENAME,SAL FROM emp WHERE  JOB = "MANAGER"  AND EMPNO IS NOT NULL ORDER BY SAL DESC LIMIT 1;
SELECT COUNT(*) FROM emp WHERE JOB = "SALESMAN" AND DEPTNO = 30;

## IIND SHEET :

SELECT DEPTNO,SUM(SAL) FROM emp WHERE JOB = "CLERK" AND DEPTNO IS NOT NULL GROUP BY DEPTNO;
SELECT DEPTNO,MAX(SAL) FROM emp WHERE DEPTNO IS NOT NULL GROUP BY DEPTNO;
SELECT * FROM emp WHERE SAL = (SELECT MAX(SAL) FROM emp WHERE JOB = "SALESMAN") AND JOB = "SALESMAN";
SELECT ENAME,SAL FROM emp WHERE JOB = "CLERK" ORDER BY HIREDATE LIMIT 1;
## Q.NO : E - ERROR
SELECT * FROM emp WHERE JOB = "CLERK" AND SAL = (SELECT MIN(SAL) FROM emp WHERE JOB = "CLERK");
SELECT * FROM emp ORDER BY HIREDATE DESC LIMIT 4;
SELECT JOB,COUNT(EMPNO) FROM emp WHERE EMPNO IS NOT NULL GROUP BY JOB;
SELECT DEPTNO,COUNT(EMPNO) FROM emp WHERE DEPTNO IS NOT NULL GROUP BY DEPTNO;
SELECT JOB,MAX(SAL) FROM emp GROUP BY JOB;
SELECT * FROM emp WHERE JOB = "CLERK" AND SAL > 800 ORDER BY SAL DESC;
## Q.NO : L - ERROR
## Q.NO : M - ERROR
SELECT * FROM emp ORDER BY ENAME;
SELECT DEPTNO,AVG(SAL) FROM emp WHERE DEPTNO IS NOT NULL GROUP BY DEPTNO;
SELECT YEAR(HIREDATE),COUNT(EMPNO) FROM emp GROUP BY YEAR(HIREDATE) ORDER BY YEAR(HIREDATE) DESC;

## IIIRD SHEET :

SELECT * FROM emp WHERE SAL = (SELECT MAX(SAL) FROM emp);
SELECT ENAME,SAL FROM emp JOIN dept ON emp.DEPTNO = dept.DEPTNO WHERE JOB = "CLERK" AND LOC = "DALLAS";
SELECT ENAME,JOB,emp.DEPTNO,DNAME,LOC FROM emp JOIN dept ON emp.DEPTNO = dept.DEPTNO WHERE JOB = "SALESMAN";
## Q.NO : D - ERROR
SELECT ENAME,SAL FROM emp JOIN dept ON emp.DEPTNO = dept.DEPTNO WHERE LOC = "CHICAGO" ORDER BY HIREDATE LIMIT 1;
SELECT ENAME,LOC FROM emp JOIN dept ON emp.DEPTNO = dept.DEPTNO WHERE ENAME = "ALLEN";
SELECT ENAME,DNAME,LOC FROM emp JOIN dept ON emp.DEPTNO = dept.DEPTNO WHERE ENAME = "SCOTT";
SELECT * FROM emp JOIN dept ON emp.DEPTNO = dept.DEPTNO WHERE DNAME = "ACCOUNTING";
SELECT emp.DEPTNO,DNAME,SUM(SAL) FROM emp JOIN dept ON emp.DEPTNO = dept.DEPTNO  GROUP BY emp.DEPTNO;
SELECT LOC,COUNT(EMPNO) FROM emp JOIN dept ON emp.DEPTNO = dept.DEPTNO WHERE EMPNO IS NOT NULL GROUP BY LOC;