CREATE TABLE Dept (
  DEPTNO int PRIMARY KEY,
  DNAME VARCHAR(14),
  LOC VARCHAR(13)
);

INSERT INTO Dept VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO Dept VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO Dept VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO Dept VALUES (40, 'OPERATIONS', 'BOSTON');

CREATE TABLE Emp (
  EMPNO int PRIMARY KEY,
  ENAME VARCHAR(10),
  JOB VARCHAR(9),
  HIREDATE DATE,
  MGR int,
  SAL int,
  COMM int,
  DEPTNO int 
);

INSERT INTO Emp VALUES 
(7369, 'SMITH', 'CLERK', '1980-12-17', 7902, 800, NULL, 20),
(7499, 'ALLEN', 'SALESMAN', '1981-02-20', 7698, 1600, 300, 30),
(7521, 'WARD', 'SALESMAN', '1981-02-22', 7698, 1250, 500, 30),
(7566, 'JONES', 'MANAGER','1981-04-02', 7839, 2975, 1400, 20),
(7654, 'MARTIN', 'SALESMAN', '1981-09-28', 7698, 1250, NULL, 30),
(7698, 'BLAKE', 'MANAGER','1981-05-01', 7839, 2850, NULL, 30),
(7782, 'CLARK', 'MANAGER', '1981-06-09', 7839, 2450, NULL, 10),
(7788, 'SCOTT', 'ANALYST', '1987-04-19', 7566, 3000, NULL, 20),
(7839, 'KING', 'PRESIDENT', '1981-11-07', NULL, 5000, NULL, 10),
(7844, 'TURNER', 'SALESMAN', '1981-09-08', 7698, 1500, 0, 30),
(7876, 'ADAMS', 'CLERK', '1987-05-23', 7788, 1100, NULL, 20),
(7900, 'JAMES', 'CLERK', '1981-12-03', 7698, 950, NULL, 30),
(7902, 'FORD', 'ANALYST','1981-12-03', 7566, 3000, NULL, 20),
(7934, 'MILLER', 'CLERK','1982-01-23', 7782, 1300,NULL,10);

SELECT LOC,COUNT(*) from Dept JOIN Emp 
on Dept.DEPTNO = Emp.DEPTNO GROUP BY LOC;

SELECT DNAME,COUNT(*) FROM Dept JOIN Emp
ON Dept.DEPTNO = Emp.DEPTNO GROUP BY DNAME;

SELECT DNAME,SUM(SAL) FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO GROUP BY DNAME;

SELECT * FROM Dept JOIN Emp 
ON Dept.DEPTNO = Emp.DEPTNO 
WHERE LOC = 'NEW YORK'  AND ENAME LIKE 'C%';

SELECT ENAME FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO 
WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM Emp) AND LOC = "DALLAS";

SELECT ENAME FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO 
WHERE SAL = (SELECT MAX(SAL) FROM Dept join Emp WHERE LOC='CHICAGO');

SELECT DNAME,MAX(SAL) FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO 
GROUP BY DNAME;

SELECT LOC,MAX(SAL) FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO 
GROUP BY LOC;

SELECT LOC,DNAME FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO 
WHERE ENAME = 'SCOTT';

SELECT COUNT(*) AS EMP_COUNT FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO 
WHERE DNAME = 'RESEARCH';

SELECT EMPNO,ENAME,JOB,HIREDATE,MGR,SAL,COMM,DNAME FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO 
WHERE DNAME = 'ACCOUNTING' ORDER BY HIREDATE;

SELECT EMPNO,ENAME,DNAME,LOC FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO
WHERE JOB = 'PRESIDENT';

SELECT ENAME,EMPNO FROM Dept JOIN Emp
ON Dept.DEPTNO = Emp.DEPTNO
WHERE SAL = (SELECT MAX(SAL) FROM Dept JOIN Emp ON Dept.DEPTNO = Emp.DEPTNO WHERE LOC = "DALLAS" AND JOB = 'CLERK')  
ORDER BY HIREDATE DESC LIMIT  1;

SELECT DNAME,COUNT(*) AS MANAGERS_COUNT FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO
WHERE JOB = 'MANAGER' GROUP BY DNAME;

SELECT ENAME,EMPNO FROM Dept JOIN Emp
ON Dept.DEPTNO = Emp.DEPTNO
WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM  Dept JOIN Emp ON Dept.DEPTNO = Emp.DEPTNO WHERE LOC = 'CHICAGO');

SELECT DNAME,AVG(SAL) AS AVG_SALARY FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO
GROUP BY DNAME;

SELECT EMPNO,ENAME,JOB,HIREDATE,MGR,SAL,COMM,DNAME FROM Dept JOIN emp
ON Dept.DEPTNO = Emp.DEPTNO
WHERE JOB = "CLERK" AND DNAME = "RESEARCH" AND HIREDATE <= '1981-01-01';


