create table Employee(Empno int(6) primary key,Ename varchar(20),Job varchar(20),Mgr int(4),Sal int(6));
alter table Employee add commission int(6);
alter table Employee modify column commission varchar(20);
insert into Employee values(1,"Pranav","Director",422164,500000,100000);
insert into Employee values(2,"Surya","Manager",422131,250000,50000);
insert into Employee values(3,"Prudhvi","Asst.Manager",422113,150000,40000);
insert into Employee values(4,"Narendra","Supervisor",422121,100000,30000);
insert into Employee values(5,"Tarun","Asst.Supervisor",422172,75000,20000);
Update Employee set Job = "Marketing Head" where Empno = "1";
Update Employee set Job = "Supervisor" where Ename = "Tarun";
alter table Employee rename column Job to Designation;
drop table Employee;
insert into Employee values(19,"Charan","Union Leader",422165,50000,10000);
delete from Employee where Empno=19;
select * from Employee;
#IInd table:
create table Department(Deptno int(6),Deptname varchar(20),location varchar(20));
select * from Department;
alter table Department add column Designation varchar(20);
insert into Department values(1,"CSE","SRK","Technical Head");
insert into Department values(2,"ECE","MMM","Cultural Head");
insert into Department values(3,"EEE","Vamsadhara","Electrical Head");
insert into Department values(4,"Mech","Nagavalli","Networking Head");
insert into Department values(5,"Civil","Pranahita","Student Affairs Head");
select* from Department where Deptno = 1;
update Department set Deptname="BIO",location="Library" where Deptno=5;
alter table Department drop column location;
#IIIrd table:
create table Customer(Cust_name varchar(20),Cust_street varchar(20),Cust_city varchar(20));
select * from Customer;
insert into Customer values("Pardhu","Temple Street","Rajahmundry");
insert into Customer values("Yeswanth","Evans street","Vijayawada");
insert into Customer values("Revanth","Ungarala street","Vijayanagaram");
insert into Customer values("Rahul","Mental street","Erra gadda");
insert into Customer values("Kapihll","clock street","Karimnagar");
alter table Customer add column Salary int(6);
insert into Customer values("Suma","Assembly Street","HYD",1000000);
alter table Customer drop column Salary;
delete from Customer where Cust_city="HYD";
#alter table Customer modify(Cust_name char(25),Cust_street char(25),Cust_city char(25));
#IVth table :
create table Branch(Branch_name varchar(20),Branch_city varchar(20),Assets int(5));
alter table Branch modify column assets int(6);
alter table Branch add column Dummy int(5);
select * from Branch;
alter table Branch drop column Dummy;
insert into Branch values("Vivekananda","Rajahmundry",1000000);
insert into Branch values("Nehru","Allahabad",500000);
insert into Branch values("LalBalPal","Delhi",4500000);
insert into Branch values("Gandhi","Porbandar",300000);
insert into Branch values("Nehru","Ahmedabad",200000);
update Branch set Branch_name="Vivekananda";
alter table Branch drop column Branch_city;
alter table Branch drop column Assets;
#Vth table :
#drop table Sailor;
create table Sailor(Sid int(6),Sname Varchar(20),rating varchar(20));
alter table Sailor add column age int(6);
insert into Sailor values(28596,"Pardhu",9.5,20);
insert into Sailor values(28790,"Surya",8.6,25);
insert into Sailor values(28694,"Amar",7.9,34);
insert into Sailor values(28367,"Gourav",8.3,48);
insert into Sailor values(28251,"Venkat",8,35);
delete from Sailor where rating>8;
update Sailor set rating=7.6;
insert into Sailor values(NULL,NULL,NULL,NULL);
select * from Sailor;
#VIth table :
create table Boats(bid int(6),bname char(20));
alter table Boats add column color char(20);
insert into Boats values(1,"Yamaha",2);
insert into Boats values(2,"Honda","Green");
insert into Boats values(3,"Suzuki","Yellow");
insert into Boats values(4,"Ford","Cement");
insert into Boats values(5,"Lamborghini","Black");
update Boats set color="Red" where bid=1;
select bid from Boats where color="Red";
select distinct color from Boats;
delete from Boats where color="Green";
select * from Boats;
#VIIth table :
create table Reserves(bid int(6),sid int(6),day int(6));
insert into Reserves values(2345,2679,1);
insert into Reserves values(25657,3456,5);
insert into Reserves values(23416,34512,2);
insert into Reserves values(23321,34521,7);
alter table Reserves add column time varchar(20);
update Reserves set time="6:30 pm" where day=1;
update Reserves set time="7:30 pm" where day=5;
update Reserves set time="8:30 pm" where day=2;
update Reserves set time="9:30 am" where day=7;
alter table reserves rename column day to date;
alter table Reserves drop column time;
delete from Reserves where date=5;
select * from Reserves;
